### ISSUE TITLE
Consider handoff between Beacon response and other GA4GH APIs

### ISSUE THREAD

**Issue by mfiume** [ga4gh-beacon/specification#68] opened 2016-12-13 15:40 UTC
We have considered how Beacons "handoff", i.e. link to, external GA4GH APIs that provide additional information about a queried variant (e.g. Variants API, MatchMaker Exchange, etc.).

We had discussed whether Beacon responses should embed these data models or link to them and (to confirm) most votes were for the latter.

Consider API changes to add the ability to link to external APIs, and consider how authorization could be brokered between systems.

**Comment by david4096** [comment] 2016-12-13 18:06
To kick off conversation I'll share a little of my experience using both the beacon and GA4GH with @almussel that you can check out [here](https://github.com/BD2KGenomics/bioapi-examples/blob/master/python_scripts/query_beacons.py). It's "the other way" from the handoff, in that I we are querying beacons based on what is in a Variant Set.

I had the issue that the beacon network response doesn't include the beacon URL. This made it so we had issues accessing the network if we got rate limited to the master node, and couldn't create our own subnetworks of beacons easily. I raised this with @mcupak so hopefully the network can be used to do this in the future.

The other place that will require some work is in how to access references using what is provided in the beacon query and choosing variant sets based on a reference set. This is a feature that has been requested at the schema level in the past that suits the beacon use case nicely.

I hope this helps. @kozbo can perhaps add some comments about the https://github.com/kozbo/Beacon-on-GA4GH-API/tree/c5be7efc199929ec9a2dbc86ec1fe80cfe945cc6 .

**Comment by jrambla** [comment] 2018-11-19 14:48
It looks like a duplicate of issue #114

**Closed** 2018-11-19 14:48 UTC
Labels: theme:Handoff, type:feature
